opt_in_rules: # some rules are only opt-in
  - empty_count
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - switch_case_alignment
  - line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
